# Generated by Django 6.0.3 on 2026-04-05 17:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_financialrecord_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than zero.')]),
        ),
    ]
